// <auto-generated />
using System;
using BookManagement.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookManagement.Migrations
{
    [DbContext(typeof(BooksContext))]
    [Migration("20230218173912_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BookManagement.Models.Books", b =>
                {
                    b.Property<int>("bookID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("bookID"));

                    b.Property<string>("bookAuthor")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("bookTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("isAvailable")
                        .HasColumnType("bit");

                    b.Property<bool?>("isShared")
                        .HasColumnType("bit");

                    b.Property<string>("sharedWith")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("bookID");

                    b.ToTable("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
